enabled = true
dll = ["HighFrameRate.dll"]

name = "High Frame Rate"
description = "This mod allows the game to run at higher frame rates, alongside replacing the game's frame rate limiter with a more precise one."
version = "1.5.0"
date = "12.03.2025"
author = "M&M, KingKrouch, Skyth, SonicFreak94, Zolika1351"